### ISSUE TITLE
syntax error in expression

### ISSUE THREAD

**Issue by alephtaph** [MarkofCain/Bible_in_Markdown#1]
Hi Mark

Fist, thank you for this script. I can't wait to have a German MD in my Obsidian.
I run in to an issue with the script.

When I run it is starting but two things happened:

1.  Alle files are named Rev-01, Rev-02... (see attached picture)
The content is correct, just the file name is wrong.
2. The script is stopping allways after "Ruth" with the following error
`build_a_bible.sh: line 93: 1 Samuel: syntax error in expression (error token is "Samuel")`

The two errors happened every time. I tried with different Bible versions (English and German)

Thank you for your help.
Marco
![Screenshot 2021-11-12 at 07 28 11](https://user-images.githubusercontent.com/82863225/141420726-5c6eeb83-405e-4529-a78c-94e86520f4db.png)
![Screenshot 2021-11-12 at 07 24 42](https://user-images.githubusercontent.com/82863225/141420734-53c5453a-13a0-4969-8d87-cb10c5dd54c4.png)
o
![Screenshot 2021-11-12 at 07 24 58](https://user-images.githubusercontent.com/82863225/141420743-03a331fc-fa61-49af-afb8-176e7ab28201.png)

**Comment by alephtaph** [comment]
Update:
The script is working fine on an Ubuntu server. So the issue must be on the Mac itself.
I have tried Mac OS 11.6 BigSur and 12.1 Monterey booth with the same issue.

**Comment by MarkofCain** [comment]
I'm glad that you got this worked out.  I wrote this script on Ubuntu and don't have a Mac test it otherwise.  I suspect that the script failed after the Book of Ruth due to the following Book (1 Samuel) being a book name that contains white space.  I'm glad that you got it to work by running it on Ubuntu.
